STOCKS = [
    {
        "symbol": "AAPL",
        "name": "Apple Inc.",
        "price": 197.24,
        "changePercent": 1.82,
        "marketCap": "$3.02T",
        "peRatio": 30.8,
        "eps": 6.42,
        "revenueGrowth": 4.1,
        "dividendYield": 0.48,
        "weekHigh52": 237.49,
        "weekLow52": 164.08,
        "volatility": 22,
        "sector": "Technology",
        "analystRating": "Moderate Buy",
        "type": "Balanced",
        "sentiment": "bullish",
    },
    {
        "symbol": "TSLA",
        "name": "Tesla Inc.",
        "price": 248.73,
        "changePercent": -2.11,
        "marketCap": "$794B",
        "peRatio": 68.4,
        "eps": 3.64,
        "revenueGrowth": 8.8,
        "dividendYield": 0,
        "weekHigh52": 299.29,
        "weekLow52": 138.8,
        "volatility": 49,
        "sector": "Consumer Cyclical",
        "analystRating": "Hold",
        "type": "Growth",
        "sentiment": "neutral",
    },
    {
        "symbol": "NVDA",
        "name": "NVIDIA Corporation",
        "price": 132.88,
        "changePercent": 3.47,
        "marketCap": "$3.26T",
        "peRatio": 54.5,
        "eps": 2.43,
        "revenueGrowth": 78.2,
        "dividendYield": 0.03,
        "weekHigh52": 153.13,
        "weekLow52": 75.61,
        "volatility": 42,
        "sector": "Semiconductors",
        "analystRating": "Strong Buy",
        "type": "Growth",
        "sentiment": "bullish",
    },
    {
        "symbol": "RELIANCE.NS",
        "name": "Reliance Industries",
        "price": 1419.55,
        "changePercent": 0.64,
        "marketCap": "INR 19.2T",
        "peRatio": 27.9,
        "eps": 50.82,
        "revenueGrowth": 6.4,
        "dividendYield": 0.35,
        "weekHigh52": 1608.8,
        "weekLow52": 1115.55,
        "volatility": 25,
        "sector": "Energy and Retail",
        "analystRating": "Buy",
        "type": "Balanced",
        "sentiment": "bullish",
    },
    {
        "symbol": "TCS.NS",
        "name": "Tata Consultancy Services",
        "price": 3898.2,
        "changePercent": -0.42,
        "marketCap": "INR 14.1T",
        "peRatio": 29.2,
        "eps": 133.5,
        "revenueGrowth": 5.9,
        "dividendYield": 1.34,
        "weekHigh52": 4592.25,
        "weekLow52": 3450.0,
        "volatility": 18,
        "sector": "IT Services",
        "analystRating": "Accumulate",
        "type": "Dividend",
        "sentiment": "neutral",
    },
]
